"""
Generate the wordmark lockup as vector paths.

    python site/tools/make-lockup.py

The word "LeastGrant" is converted to outlines from IBM Plex Mono SemiBold --
the face the site already sets its headings in -- rather than drawn by hand.
Hand-drawing ten letterforms on a grid sounds cheap and is not: the first
attempt at this produced a lockup that read "LedstGrdnt", because a hand-built
`a` at 32 units is one wrong coordinate away from a `d`.

Converting from the real face means the lockup is typographically identical to
the site's own headings, and the output is plain `<path>` data with no font
dependency at render time.

Run when the mark or the wordmark changes. The output is committed.
"""

import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

ROOT = Path(__file__).resolve().parents[2]
FONT = ROOT / "site" / "assets" / "fonts" / "IBMPlexMono-SemiBold.woff2"
OUT = ROOT / "site" / "static" / "logo-lockup.svg"

WORD = "LeastGrant"

# The mark, from site/lib/brand.mjs. Kept in sync by the assertion below.
MARK = '<path d="M4.25 2V27.75H30"/><path d="M30 7.5H14.5V21H30V14.5H22.5"/>'

brand = (ROOT / "site" / "lib" / "brand.mjs").read_text(encoding="utf-8")
if MARK not in brand:
    sys.exit(
        "the mark geometry in this script no longer matches site/lib/brand.mjs.\n"
        "brand.mjs is the source of truth -- copy MARK_PATHS across and re-run."
    )


def main() -> None:
    if not FONT.exists():
        sys.exit(f"missing {FONT}")

    font = TTFont(FONT)
    upem = font["head"].unitsPerEm
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()

    # Cap height sets the optical size: the wordmark's caps should match the
    # mark's height so the two sit on one visual line.
    cap = font["OS/2"].sCapHeight if hasattr(font["OS/2"], "sCapHeight") else int(upem * 0.7)

    # Target: caps 18 units tall on the 32-unit grid, baseline at y = 24.
    target_cap = 18.0
    scale = target_cap / cap
    baseline = 24.0

    pen_paths = []
    x = 0.0
    for char in WORD:
        name = cmap.get(ord(char))
        if name is None:
            sys.exit(f"no glyph for {char!r}")
        glyph = glyph_set[name]

        pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.2f}")
        # y is flipped: font space is up-positive, SVG is down-positive.
        transform = Transform(scale, 0, 0, -scale, x, baseline)
        glyph.draw(TransformPen(pen, transform))
        d = pen.getCommands()
        if d:
            pen_paths.append(d)
        x += glyph.width * scale

    width = x
    gap = 11.0  # air between the mark and the L, a little over a third of the mark
    text_x = 32 + gap
    total = text_x + width + 1

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {total:.0f} 32" role="img" aria-label="LeastGrant">
  <title>LeastGrant</title>
  <!--
    Lockup: the mark, then the wordmark set in IBM Plex Mono SemiBold and
    converted to outlines. Generated by site/tools/make-lockup.py; do not edit
    the path data by hand.
  -->
  <g fill="none" stroke="currentColor" stroke-width="4.5" stroke-linecap="butt" stroke-linejoin="miter">
    {MARK}
  </g>
  <g transform="translate({text_x:.2f} 0)" fill="currentColor">
    <path d="{' '.join(pen_paths)}"/>
  </g>
</svg>
"""

    OUT.write_text(svg, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}  viewBox 0 0 {total:.0f} 32  ({len(svg)} bytes)")


if __name__ == "__main__":
    main()
