/**
 * Regenerate the README's agent-support section from `compatibility/*.json`.
 *
 * That table was written by hand, and by the time the second audit read it, six
 * of its claims were contradicted by the repo's own data — including "an ask
 * reaches you in every mode" on Claude Code, which is false under `claude -p`,
 * and "a real ask" for Codex modes where nothing prompts. Every one of those
 * was true when it was written. That is the problem with a hand-written table:
 * it decays silently, and the decay is invisible precisely because it reads
 * fluently.
 *
 * So the same file that `leastgrant doctor` and the website render now also
 * produces this. Four surfaces, one source. `npm run gen:readme` rewrites the
 * marked block; `test/readme-generated.test.ts` fails if the committed README
 * does not match what this would produce, so the drift cannot survive CI.
 *
 * What is NOT generated: the prose either side of the block. Voice is worth
 * keeping and a generator writes badly. What the generator owns is every
 * falsifiable claim — which agent, which version, what is enforced, what is
 * not.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCompatibility } from '../dist/src/core/compatibility.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const README = path.join(ROOT, 'README.md');
const BEGIN = '<!-- BEGIN generated: agent-support -->';
const END = '<!-- END generated: agent-support -->';

/** How a verdict value reads in a table cell. */
const VERDICT = {
  honoured: 'yes',
  ignored: 'ignored',
  unsupported: 'no',
  degrades: 'degrades',
  partial: 'partial',
  unknown: '?',
};

/**
 * Status words, deliberately unstyled.
 *
 * They are compared verbatim against the rendered site by
 * `site/test/build.test.mjs`, which asserts that whatever status the README
 * gives an agent is the status a visitor sees. Markdown emphasis here would
 * survive into the README and not into the HTML, and the two would silently
 * stop being comparable.
 */
const STATUS = {
  enforcing: 'Enforcing',
  partial: 'Partial',
  'evaluated-not-yet-shipped': 'Evaluated, no adapter',
  'evaluated-and-deferred': 'Evaluated, deferred',
  none: 'Not yet',
};

const cell = (v) => VERDICT[String(v)] ?? String(v ?? '?');
const value = (a, group, key) => a?.[group]?.[key]?.value;

export function render() {
  const agents = loadCompatibility();
  const shipped = agents.filter((a) => a.adapter);
  const evaluated = agents.filter((a) => !a.adapter);

  const rows = shipped.map((a) => {
    const crash = value(a, 'failure', 'onCrash');
    return `| **${a.name}** | ${STATUS[a.supported] ?? a.supported} | ${cell(value(a, 'verdicts', 'allow'))} | ${cell(value(a, 'verdicts', 'ask'))} | ${cell(value(a, 'verdicts', 'deny'))} | ${crash === 'closed' ? 'refuses' : crash === 'open' ? 'runs anyway' : '?'} | ${a.versionTested ?? '—'}${(a.osTested ?? []).length ? ` on ${a.osTested.join(', ')}` : ', not run live'} |`;
  });

  const out = [
    BEGIN,
    '',
    '<!-- Generated by scripts/gen-readme.mjs from compatibility/*.json. Do not edit by hand. -->',
    '',
    '| Agent | Status | allow | ask | deny | if the hook breaks | verified against |',
    '|---|---|---|---|---|---|---|',
    ...rows,
    '',
    '`ask` is the column that matters and the one that differs most. `yes` means a',
    'prompt reaches a person. `degrades` means it reaches them where a prompt',
    'surface exists and becomes a deny where none does. `no` means the agent has no',
    'ask at all, so LeastGrant is a veto there rather than a question.',
    '',
    '**What each one cannot do.** Not a disclaimer — the point of the table above is',
    'that this list exists and is specific.',
    '',
  ];

  for (const a of shipped) {
    const limits = [...(a.upstreamLimitations ?? []), ...(a.leastgrantLimitations ?? [])];
    if (!limits.length) continue;
    out.push(`- **${a.name}.** ${limits.join(' ')}`);
  }

  if (evaluated.length) {
    out.push('');
    out.push('**Looked at, no adapter shipped.**');
    out.push('');
    for (const a of evaluated) {
      const why = a.deferredBecause ?? a.$comment ?? `${STATUS[a.supported] ?? a.supported}.`;
      out.push(`- **${a.name}** (${a.versionTested ?? 'version not recorded'}). ${why}`);
    }
  }

  out.push('');
  out.push(END);
  return out.join('\n');
}

export function currentBlock(readme = fs.readFileSync(README, 'utf8')) {
  const from = readme.indexOf(BEGIN);
  const to = readme.indexOf(END);
  if (from === -1 || to === -1) return null;
  return readme.slice(from, to + END.length);
}

/**
 * Compare without caring about line endings.
 *
 * git is configured to convert on checkout here, so the committed README
 * arrives with CRLF while this file emits LF, and a byte comparison reports
 * drift on every line of an identical table. That would make the check
 * unfixable by running the generator, which is the one instruction the failure
 * message gives.
 */
const lf = (s) => s.split('\r\n').join('\n');

export function apply() {
  const readme = fs.readFileSync(README, 'utf8');
  const from = readme.indexOf(BEGIN);
  const to = readme.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error(`README.md has no ${BEGIN} / ${END} block to fill`);
  }
  // Keep whatever line ending the file already uses, so writing the block does
  // not rewrite every line of the README in the diff.
  const crlf = readme.includes('\r\n');
  const block = crlf ? render().split('\n').join('\r\n') : render();
  const next = readme.slice(0, from) + block + readme.slice(to + END.length);
  if (next === readme) return false;
  fs.writeFileSync(README, next);
  return true;
}

if (process.argv[1]?.endsWith('gen-readme.mjs')) {
  if (process.argv.includes('--check')) {
    // Exits non-zero on drift, so CI and the test suite can both use it without
    // importing this file — it is .mjs and the suite is typed.
    const current = currentBlock();
    if (current === null) {
      console.error('README.md has lost its generated-block markers');
      process.exit(1);
    }
    if (lf(current) !== lf(render())) {
      console.error('README.md agent table is out of date. Run: npm run gen:readme');
      process.exit(1);
    }
    console.log('README.md agent table is up to date');
  } else {
    const changed = apply();
    console.log(changed ? 'README.md agent-support block updated' : 'README.md already up to date');
  }
}
